### PR TITLE
🐳 Dockerize ShotAPI

### PR DESCRIPTION
**Pull request by lissy93**
Hey @arshad-yaseen
Nice project! Just thought I'd add my contribution, a lil Dockerfile for easier deployment.
 It's all tested and working, but feel free to let me know if you'd like me to change anything in it.

### Usage
```bash
# Build the Docker image
docker build -t shotapi .

# Run the Docker container
docker run -p 8000:8000 shotapi
```

### CODE REVIEW

**Comment by lissy93** [comment]
I didn't think it necessary to add a docker-compose, since the run command is pretty simple.
But if you'd like one, I used the following, and ran `docker compose up`

```yaml
version: '3.8'

services:
  shotapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
```

---

And if you're interested, I/you can add a GitHub workflow to publish the container to DockerHub / GHCR

<details>

<summary>Example</summary>

The `.github/workflows/publish-docker.yml` would be something like this:

```yaml
name: 🐳 Build + Publish Multi-Platform Image

on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['*']
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'pyproject.toml'

env:
  DH_IMAGE: arshad-yaseen/shotapi
  GH_IMAGE: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
    - name: 🛎️ Checkout Repo
      uses: actions/checkout@v2

    - name: 🗂️ Make Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.DH_IMAGE }}
          ghcr.io/${{ env.GH_IMAGE }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch
          type=ref,event=tag
        labels: |
          maintainer=Lissy93
          org.opencontainers.image.title=ShotAPI
          org.opencontainers.image.description=Capture screenshot of a webpage without headache
          org.opencontainers.image.documentation=https://shotapi.arshadyaseen.com
          org.opencontainers.image.authors=Arshad-Yaseen
          org.opencontainers.image.licenses=MIT

    - name: 🔧 Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: 🔧 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 🔑 Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: arshad-yaseen
        password: ${{ secrets.DOCKERHUB_API_KEY }}

    - name: 🔑 Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🚦 Check Registry Status
      uses: crazy-max/ghaction-docker-status@v1

    - name: ⚒️ Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true       
```

(adapted from [this](https://github.com/Lissy93/dashy/blob/master/.github/workflows/docker-build-publish.yml) and [this](https://github.com/Lissy93/who-dat/blob/main/.github/workflows/docker-build-publish.yml) - both of which work good) You'd just need to set the `GITHUB_TOKEN` and `DOCKERHUB_API_KEY` in your repo secrets, and check the env vars are what you'd like them to be.

</details>

**Comment by arshad-yaseen** [comment]
Hey @Lissy93, I'm glad you're the first contributor.

I initially tried using `Docker`, but I encountered numerous errors related to `Chromium` and other issues. After several unsuccessful attempts, I decided to deploy on `Render.com` because it offers built-in support for Chromium. It's user-friendly and also provides a GitHub PR preview URL, among other features.

I'm aware that the Docker configuration you implemented works, but when I tried it, I faced some errors with Selenium. If it's working for you, perhaps the issues are on my end.

Would you be interested in becoming a maintainer of ShotAPI? ShotAPI is the world's first open-source website screenshot API. You can look it up.

If you're interested, I'll grant you access. Together, we can enhance ShotAPI to the next level. I know you're enthusiastic in open-source.

As a maintainer, you can attempt deployment with Docker and make any changes you see fit.

Our current deployment plan is the starter package, which delivers screenshots within an average of 12 to 15 seconds. If you could deploy on a different platform like AWS, that might be more efficient. I've tried the pro ultra plan on Render.com, and the response time improved to between 1 and 3 seconds.

What are your thoughts?

**Comment by lissy93** [comment]
Sure, I'd be happy to help :)

An re the Docker image, what error message do you get with Selinium? Being in Docker, it shouldn't really be impacted by your host machine, but if you pop open the repo in CodeSpaces (click Code in the top right of the PR), do you still get the error? Eitherway, it won't affect deployment to Render.com, but will just give users another option for deploying to other platforms.

**Comment by arshad-yaseen** [comment]
Ohh yess, It's worked. Thanks a lot @Lissy93 🌸

**Review by arshad-yaseen — APPROVED** [review]
✅

Merging...

**Pull request merged**
